"""adds

Revision ID: 5adfd302e336
Revises: d12d84ec5eaa
Create Date: 2024-09-11 11:22:26.625699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adfd302e336'
down_revision = 'd12d84ec5eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_column('token_cost')

    # ### end Alembic commands ###
