"""ad

Revision ID: b5e1ae8b0f0f
Revises: 5adfd302e336
Create Date: 2024-09-17 11:34:25.941538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e1ae8b0f0f'
down_revision = '5adfd302e336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))  # Allow NULL temporarily
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))  # Similarly for other columns
        batch_op.add_column(sa.Column('replied_phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_column('replied_phone_number')
        batch_op.drop_column('token')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
