"""add

Revision ID: d12d84ec5eaa
Revises: 870084f411f8
Create Date: 2024-09-11 08:15:28.800565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12d84ec5eaa'
down_revision = '870084f411f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replied_phone_number', sa.String(length=15), nullable=True))
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('replied_phone_number')

    # ### end Alembic commands ###
