"""fi

Revision ID: d9dcb5b4ab78
Revises: cb7f205744a2
Create Date: 2024-09-08 10:46:56.044710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9dcb5b4ab78'
down_revision = 'cb7f205744a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['token_id'])
        batch_op.create_foreign_key(None, 'token', ['token_id'], ['id'])

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qa_id', sa.UUID(), nullable=True))
        batch_op.drop_constraint('token_auth_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'qa', ['qa_id'], ['id'])
        batch_op.drop_column('auth_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('token_auth_id_fkey', 'auth', ['auth_id'], ['id'])
        batch_op.drop_column('qa_id')

    with op.batch_alter_table('auth', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_id')

    # ### end Alembic commands ###
